/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import { Provider, TransactionRequest } from "@ethersproject/providers";
import type {
  MyExternalHandlerExample,
  MyExternalHandlerExampleInterface,
} from "../MyExternalHandlerExample";

const _abi = [
  {
    anonymous: false,
    inputs: [
      {
        indexed: false,
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        indexed: false,
        internalType: "address",
        name: "ticketOwner",
        type: "address",
      },
    ],
    name: "TicketAction",
    type: "event",
  },
  {
    inputs: [
      {
        internalType: "address",
        name: "sender",
        type: "address",
      },
      {
        internalType: "address",
        name: "ticketOwner",
        type: "address",
      },
    ],
    name: "ticketAction",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b5061011d806100206000396000f3fe6080604052348015600f57600080fd5b506004361060285760003560e01c8063d628af0314602d575b600080fd5b603c603836600460ba565b603e565b005b6040805173ffffffffffffffffffffffffffffffffffffffff8085168252831660208201527fa0f4e3d3506a5e72e1376a1a86c1406c1da27b45cdc554ed4b8b40aa14649eb1910160405180910390a15050565b803573ffffffffffffffffffffffffffffffffffffffff8116811460b557600080fd5b919050565b6000806040838503121560cb578182fd5b60d2836092565b915060de602084016092565b9050925092905056fea2646970667358221220f8162d0d3461cb02ac8d5bcadc579f94a0d17d3d519cc104ddfeb99f3159ef0364736f6c63430008040033";

export class MyExternalHandlerExample__factory extends ContractFactory {
  constructor(
    ...args: [signer: Signer] | ConstructorParameters<typeof ContractFactory>
  ) {
    if (args.length === 1) {
      super(_abi, _bytecode, args[0]);
    } else {
      super(...args);
    }
  }

  deploy(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): Promise<MyExternalHandlerExample> {
    return super.deploy(overrides || {}) as Promise<MyExternalHandlerExample>;
  }
  getDeployTransaction(
    overrides?: Overrides & { from?: string | Promise<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  attach(address: string): MyExternalHandlerExample {
    return super.attach(address) as MyExternalHandlerExample;
  }
  connect(signer: Signer): MyExternalHandlerExample__factory {
    return super.connect(signer) as MyExternalHandlerExample__factory;
  }
  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): MyExternalHandlerExampleInterface {
    return new utils.Interface(_abi) as MyExternalHandlerExampleInterface;
  }
  static connect(
    address: string,
    signerOrProvider: Signer | Provider
  ): MyExternalHandlerExample {
    return new Contract(
      address,
      _abi,
      signerOrProvider
    ) as MyExternalHandlerExample;
  }
}
