/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { ethers } from "ethers";
import {
  FactoryOptions,
  HardhatEthersHelpers as HardhatEthersHelpersBase,
} from "@nomiclabs/hardhat-ethers/types";

import * as Contracts from ".";

declare module "hardhat/types/runtime" {
  interface HardhatEthersHelpers extends HardhatEthersHelpersBase {
    getContractFactory(
      name: "MyExternalHandlerExample",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.MyExternalHandlerExample__factory>;
    getContractFactory(
      name: "Verifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.Verifier__factory>;
    getContractFactory(
      name: "ExternalTicketHandler",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ExternalTicketHandler__factory>;
    getContractFactory(
      name: "IVerifier",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.IVerifier__factory>;
    getContractFactory(
      name: "ZKTickets",
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<Contracts.ZKTickets__factory>;

    getContractAt(
      name: "MyExternalHandlerExample",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.MyExternalHandlerExample>;
    getContractAt(
      name: "Verifier",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.Verifier>;
    getContractAt(
      name: "ExternalTicketHandler",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ExternalTicketHandler>;
    getContractAt(
      name: "IVerifier",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.IVerifier>;
    getContractAt(
      name: "ZKTickets",
      address: string,
      signer?: ethers.Signer
    ): Promise<Contracts.ZKTickets>;

    // default types
    getContractFactory(
      name: string,
      signerOrOptions?: ethers.Signer | FactoryOptions
    ): Promise<ethers.ContractFactory>;
    getContractFactory(
      abi: any[],
      bytecode: ethers.utils.BytesLike,
      signer?: ethers.Signer
    ): Promise<ethers.ContractFactory>;
    getContractAt(
      nameOrAbi: string | any[],
      address: string,
      signer?: ethers.Signer
    ): Promise<ethers.Contract>;
  }
}
